import type { BallProfile, CompetitionProfile, SurfaceProfile, TrophyProfile, VenueProfile, WorldSelection } from './types'

export const SURFACES: SurfaceProfile[] = [
  { id: 'elite-hybrid', name: 'Elite hybrid grass', type: 'hybrid', grassLengthMm: 24, bladeDensity: 0.96, moisture: 0.42, hardness: 0.58, drainage: 0.94, slope: 0.006, rollingResistance: 0.98, bounce: 1, grip: 0.94, mudPotential: 0.12, waterloggingRisk: 0.06, lineDurability: 0.96, maintenanceCost: 0.95 },
  { id: 'highland-natural', name: 'Highland natural grass', type: 'natural', grassLengthMm: 27, bladeDensity: 0.84, moisture: 0.48, hardness: 0.54, drainage: 0.76, slope: 0.008, rollingResistance: 1.03, bounce: 0.96, grip: 0.88, mudPotential: 0.3, waterloggingRisk: 0.18, lineDurability: 0.82, maintenanceCost: 0.66 },
  { id: 'regional-grass', name: 'Regional natural grass', type: 'natural', grassLengthMm: 31, bladeDensity: 0.7, moisture: 0.36, hardness: 0.64, drainage: 0.58, slope: 0.012, rollingResistance: 1.12, bounce: 1.06, grip: 0.77, mudPotential: 0.42, waterloggingRisk: 0.35, lineDurability: 0.68, maintenanceCost: 0.45 },
  { id: 'dry-community', name: 'Dry community grass', type: 'dry-grass', grassLengthMm: 34, bladeDensity: 0.48, moisture: 0.16, hardness: 0.82, drainage: 0.52, slope: 0.018, rollingResistance: 1.18, bounce: 1.18, grip: 0.68, mudPotential: 0.15, waterloggingRisk: 0.22, lineDurability: 0.52, maintenanceCost: 0.22 },
  { id: 'community-dirt', name: 'Community dirt field', type: 'dirt', grassLengthMm: 0, bladeDensity: 0.04, moisture: 0.12, hardness: 0.72, drainage: 0.4, slope: 0.026, rollingResistance: 1.34, bounce: 1.22, grip: 0.61, mudPotential: 0.72, waterloggingRisk: 0.46, lineDurability: 0.38, maintenanceCost: 0.08 },
  { id: 'academy-artificial', name: 'Academy artificial turf', type: 'artificial', grassLengthMm: 38, bladeDensity: 0.9, moisture: 0.18, hardness: 0.7, drainage: 0.9, slope: 0.004, rollingResistance: 0.9, bounce: 1.1, grip: 0.91, mudPotential: 0, waterloggingRisk: 0.03, lineDurability: 1, maintenanceCost: 0.56 },
  { id: 'futsal-court', name: 'Indoor futsal court', type: 'futsal', grassLengthMm: 0, bladeDensity: 0, moisture: 0, hardness: 0.94, drainage: 1, slope: 0, rollingResistance: 0.72, bounce: 0.82, grip: 0.96, mudPotential: 0, waterloggingRisk: 0, lineDurability: 1, maintenanceCost: 0.52 },
]

export const BALLS: BallProfile[] = [
  { id: 'nile-pro', name: 'Nile Pro Match', category: 'official', size: 5, massKg: 0.43, panelCount: 14, seamDepthMm: 0.9, pressureBar: 0.82, waterAbsorption: 0.03, dragCoefficient: 0.19, magnusCoefficient: 1, restitution: 0.46, rollingFriction: 0.98, spinRetention: 0.94, roughness: 0.5, baseColor: '#f5f1e6', accentColor: '#14834f', highVisibility: false },
  { id: 'abyssinia-final', name: 'Abyssinia Final Gold', category: 'final', size: 5, massKg: 0.432, panelCount: 12, seamDepthMm: 0.72, pressureBar: 0.84, waterAbsorption: 0.02, dragCoefficient: 0.18, magnusCoefficient: 1.04, restitution: 0.47, rollingFriction: 0.96, spinRetention: 0.96, roughness: 0.44, baseColor: '#f4e7bf', accentColor: '#b78a2c', highVisibility: false },
  { id: 'highland-winter', name: 'Highland Visibility', category: 'winter', size: 5, massKg: 0.435, panelCount: 18, seamDepthMm: 1.05, pressureBar: 0.8, waterAbsorption: 0.025, dragCoefficient: 0.2, magnusCoefficient: 0.98, restitution: 0.44, rollingFriction: 1.02, spinRetention: 0.91, roughness: 0.56, baseColor: '#f35c24', accentColor: '#181b1a', highVisibility: true },
  { id: 'academy-control', name: 'Academy Control', category: 'training', size: 5, massKg: 0.44, panelCount: 32, seamDepthMm: 1.35, pressureBar: 0.76, waterAbsorption: 0.08, dragCoefficient: 0.22, magnusCoefficient: 0.92, restitution: 0.43, rollingFriction: 1.06, spinRetention: 0.88, roughness: 0.62, baseColor: '#ecebe4', accentColor: '#2a65a4', highVisibility: false },
  { id: 'futsal-low-bounce', name: 'Futsal Low Bounce', category: 'futsal', size: 4, massKg: 0.41, panelCount: 12, seamDepthMm: 0.8, pressureBar: 0.62, waterAbsorption: 0, dragCoefficient: 0.24, magnusCoefficient: 0.82, restitution: 0.28, rollingFriction: 0.74, spinRetention: 0.98, roughness: 0.52, baseColor: '#f3dd2e', accentColor: '#14233e', highVisibility: true },
  { id: 'street-durable', name: 'Street Durable', category: 'street', size: 5, massKg: 0.445, panelCount: 32, seamDepthMm: 1.55, pressureBar: 0.74, waterAbsorption: 0.12, dragCoefficient: 0.23, magnusCoefficient: 0.86, restitution: 0.5, rollingFriction: 1.16, spinRetention: 0.82, roughness: 0.72, baseColor: '#d9d0b8', accentColor: '#b43c32', highVisibility: false },
  { id: 'heritage-leather', name: 'Heritage Leather', category: 'vintage', size: 5, massKg: 0.47, panelCount: 18, seamDepthMm: 2.4, pressureBar: 0.68, waterAbsorption: 0.24, dragCoefficient: 0.29, magnusCoefficient: 0.7, restitution: 0.38, rollingFriction: 1.2, spinRetention: 0.72, roughness: 0.82, baseColor: '#8d5d35', accentColor: '#3c281b', highVisibility: false },
  { id: 'community-standard', name: 'Community Standard', category: 'community', size: 5, massKg: 0.455, panelCount: 32, seamDepthMm: 1.7, pressureBar: 0.72, waterAbsorption: 0.14, dragCoefficient: 0.25, magnusCoefficient: 0.84, restitution: 0.42, rollingFriction: 1.12, spinRetention: 0.79, roughness: 0.68, baseColor: '#ddd8c8', accentColor: '#2f754a', highVisibility: false },
]

export const TROPHIES: TrophyProfile[] = [
  { id: 'league-crown', name: 'National League Crown', material: 'brushed gold and dark stone', massKg: 8.4, heightCm: 68, handles: true, ribbons: true, engraving: true, ceremonyTier: 'league' },
  { id: 'federation-cup', name: 'Federation Cup', material: 'silver and green enamel', massKg: 6.7, heightCm: 58, handles: true, ribbons: true, engraving: true, ceremonyTier: 'continental' },
  { id: 'continental-star', name: 'Continental Star', material: 'gold-plated brass and obsidian', massKg: 11.2, heightCm: 76, handles: false, ribbons: true, engraving: true, ceremonyTier: 'final' },
  { id: 'community-shield', name: 'Community Shield', material: 'polished bronze and hardwood', massKg: 4.2, heightCm: 42, handles: false, ribbons: false, engraving: true, ceremonyTier: 'local' },
  { id: 'youth-cup', name: 'Academy Future Cup', material: 'silver aluminium and blue enamel', massKg: 3.8, heightCm: 46, handles: true, ribbons: true, engraving: true, ceremonyTier: 'local' },
  { id: 'futsal-cup', name: 'Futsal Prism', material: 'polished steel and crystal acrylic', massKg: 4.9, heightCm: 51, handles: false, ribbons: false, engraving: true, ceremonyTier: 'league' },
]

export const COMPETITIONS: CompetitionProfile[] = [
  { id: 'ethiopian-premier', name: 'Ethiopian Premier League', shortName: 'EPL', region: 'Ethiopia', format: 'round-robin', teams: 16, legs: 2, prestige: 0.82, colors: ['#0f7a46', '#e2bc38', '#b93639'], typography: 'broadcast', trophyId: 'league-crown', officialBallId: 'nile-pro', ceremonyTier: 'league', crowdMultiplier: 1, mediaMultiplier: 0.9, securityMultiplier: 0.9, musicStyle: 'Ethiopian modern brass and percussion', entranceStyle: 'league walkout', broadcastStyle: 'Prime Ethiopian Broadcast', tiebreakers: ['points', 'goal-difference', 'goals-scored', 'head-to-head', 'fair-play', 'lots'], extraTime: false, penalties: false, substitutions: 5, visualIdentity: 'Green, gold and red precision package with Amharic and English field graphics.' },
  { id: 'ethiopian-cup', name: 'Ethiopian Federation Cup', shortName: 'EFC', region: 'Ethiopia', format: 'single-elimination', teams: 32, legs: 1, prestige: 0.86, colors: ['#f2f0df', '#1a7548', '#c43d3f'], typography: 'heritage', trophyId: 'federation-cup', officialBallId: 'abyssinia-final', ceremonyTier: 'continental', crowdMultiplier: 1.08, mediaMultiplier: 1.08, securityMultiplier: 1.04, musicStyle: 'Ceremonial strings, masenqo textures and percussion', entranceStyle: 'cup banner and trophy plinth', broadcastStyle: 'Heritage Cup', tiebreakers: ['goal-difference', 'away-goals', 'fair-play', 'lots'], extraTime: true, penalties: true, substitutions: 5, visualIdentity: 'Ivory heritage package with etched geometric borders and cup-specific replay wipes.' },
  { id: 'continental-champions', name: 'African Continental Champions Cup', shortName: 'ACC', region: 'Africa', format: 'groups-knockout', teams: 32, groupCount: 8, legs: 2, prestige: 1, colors: ['#171b2c', '#e0af32', '#f4f0e6'], typography: 'modern', trophyId: 'continental-star', officialBallId: 'abyssinia-final', ceremonyTier: 'final', crowdMultiplier: 1.2, mediaMultiplier: 1.35, securityMultiplier: 1.25, musicStyle: 'Continental cinematic orchestra and regional percussion', entranceStyle: 'anthem, giant flag and trophy display', broadcastStyle: 'Continental Night', tiebreakers: ['points', 'head-to-head', 'goal-difference', 'goals-scored', 'fair-play', 'lots'], extraTime: true, penalties: true, substitutions: 5, visualIdentity: 'Midnight blue and gold package with star geometry and monumental finals presentation.' },
  { id: 'national-team-cup', name: 'National Team Championship', shortName: 'NTC', region: 'International', format: 'groups-knockout', teams: 24, groupCount: 6, legs: 1, prestige: 0.96, colors: ['#147d49', '#e3c238', '#c63f3d'], typography: 'heritage', trophyId: 'continental-star', officialBallId: 'nile-pro', ceremonyTier: 'final', crowdMultiplier: 1.22, mediaMultiplier: 1.3, securityMultiplier: 1.25, musicStyle: 'National ceremonial and stadium orchestra', entranceStyle: 'flags and national anthem protocol', broadcastStyle: 'National Honour', tiebreakers: ['points', 'goal-difference', 'goals-scored', 'fair-play', 'lots'], extraTime: true, penalties: true, substitutions: 5, visualIdentity: 'Respectful national colors, correct flag protocol and multilingual graphics.' },
  { id: 'regional-cup', name: 'Regional Cities Cup', shortName: 'RCC', region: 'Ethiopia', format: 'groups-knockout', teams: 16, groupCount: 4, legs: 1, prestige: 0.64, colors: ['#244a63', '#e2a743', '#e9eee9'], typography: 'community', trophyId: 'community-shield', officialBallId: 'community-standard', ceremonyTier: 'local', crowdMultiplier: 0.88, mediaMultiplier: 0.55, securityMultiplier: 0.72, musicStyle: 'Regional rhythms and local public-address presentation', entranceStyle: 'regional banners and simple handshakes', broadcastStyle: 'Regional Live', tiebreakers: ['points', 'goal-difference', 'goals-scored', 'head-to-head', 'lots'], extraTime: true, penalties: true, substitutions: 5, visualIdentity: 'City-led colors with localized signage and restrained ceremony.' },
  { id: 'women-premier', name: 'Ethiopian Women’s Premier League', shortName: 'EWPL', region: 'Ethiopia', format: 'round-robin', teams: 12, legs: 2, prestige: 0.74, colors: ['#6f3f91', '#e1bd3c', '#f5f0e5'], typography: 'modern', trophyId: 'league-crown', officialBallId: 'nile-pro', ceremonyTier: 'league', crowdMultiplier: 0.82, mediaMultiplier: 0.76, securityMultiplier: 0.8, musicStyle: 'Modern Ethiopian pop-instrumental and percussion', entranceStyle: 'league walkout and equality presentation', broadcastStyle: 'Women’s Prime', tiebreakers: ['points', 'goal-difference', 'goals-scored', 'head-to-head', 'fair-play'], extraTime: false, penalties: false, substitutions: 5, visualIdentity: 'Purple, gold and ivory contemporary package with equal broadcast depth.' },
  { id: 'academy-league', name: 'National Academy League', shortName: 'NAL', region: 'Ethiopia', format: 'split-league', teams: 20, legs: 2, prestige: 0.54, colors: ['#2766a0', '#f0b43e', '#f5f2ea'], typography: 'modern', trophyId: 'youth-cup', officialBallId: 'academy-control', ceremonyTier: 'local', crowdMultiplier: 0.52, mediaMultiplier: 0.38, securityMultiplier: 0.48, musicStyle: 'Youthful instrumental and school percussion', entranceStyle: 'compact academy lineup', broadcastStyle: 'Future Stars', tiebreakers: ['points', 'goal-difference', 'goals-scored', 'head-to-head', 'fair-play'], extraTime: false, penalties: false, substitutions: 7, visualIdentity: 'Blue and amber youth-development package with player-development statistics.' },
  { id: 'university-cup', name: 'University Football Cup', shortName: 'UFC', region: 'Ethiopia', format: 'swiss', teams: 24, legs: 1, prestige: 0.48, colors: ['#254f45', '#d67c35', '#ece9dd'], typography: 'community', trophyId: 'community-shield', officialBallId: 'community-standard', ceremonyTier: 'local', crowdMultiplier: 0.48, mediaMultiplier: 0.32, securityMultiplier: 0.42, musicStyle: 'Campus bands and regional instrumentals', entranceStyle: 'campus banners and team photographs', broadcastStyle: 'Campus Football', tiebreakers: ['points', 'goal-difference', 'goals-scored', 'fair-play', 'lots'], extraTime: true, penalties: true, substitutions: 7, visualIdentity: 'Campus-led identity with institution colors and student atmosphere.' },
  { id: 'community-knockout', name: 'Community Neighbourhood Cup', shortName: 'CNC', region: 'Local', format: 'single-elimination', teams: 16, legs: 1, prestige: 0.3, colors: ['#8f5434', '#e1c14a', '#f1e4ca'], typography: 'community', trophyId: 'community-shield', officialBallId: 'community-standard', ceremonyTier: 'local', crowdMultiplier: 0.34, mediaMultiplier: 0.12, securityMultiplier: 0.24, musicStyle: 'Local speaker, clapping and community percussion', entranceStyle: 'short handshake and community banner', broadcastStyle: 'Community Live', tiebreakers: ['fair-play', 'lots'], extraTime: false, penalties: true, substitutions: 7, visualIdentity: 'Warm earth colors, hand-painted boards and respectful neighbourhood identity.' },
  { id: 'futsal-championship', name: 'National Futsal Championship', shortName: 'NFC', region: 'Ethiopia', format: 'groups-knockout', teams: 16, groupCount: 4, legs: 1, prestige: 0.62, colors: ['#12223d', '#f5ca3d', '#e54b45'], typography: 'modern', trophyId: 'futsal-cup', officialBallId: 'futsal-low-bounce', ceremonyTier: 'league', crowdMultiplier: 0.56, mediaMultiplier: 0.54, securityMultiplier: 0.52, musicStyle: 'Fast electronic rhythm with Ethiopian percussion', entranceStyle: 'indoor light sequence', broadcastStyle: 'Futsal Pulse', tiebreakers: ['points', 'goal-difference', 'goals-scored', 'head-to-head', 'fair-play'], extraTime: true, penalties: true, substitutions: 12, visualIdentity: 'High-contrast indoor package with fast clock and rolling-substitution graphics.' },
  { id: 'charity-match', name: 'Unity Charity Match', shortName: 'UNITY', region: 'Ethiopia', format: 'best-of-series', teams: 2, legs: 1, prestige: 0.46, colors: ['#168150', '#e0bd3d', '#c53c3b'], typography: 'heritage', trophyId: 'community-shield', officialBallId: 'nile-pro', ceremonyTier: 'local', crowdMultiplier: 0.74, mediaMultiplier: 0.72, securityMultiplier: 0.7, musicStyle: 'Unity ceremonial instrumental', entranceStyle: 'charity banner and community representatives', broadcastStyle: 'Unity Broadcast', tiebreakers: ['fair-play', 'lots'], extraTime: false, penalties: true, substitutions: 9, visualIdentity: 'National unity palette with charity messaging and respectful community focus.' },
  { id: 'promotion-playoff', name: 'Promotion and Relegation Playoff', shortName: 'PLAYOFF', region: 'Ethiopia', format: 'promotion-playoff', teams: 4, legs: 2, prestige: 0.76, colors: ['#20292d', '#e0a735', '#f1eee5'], typography: 'broadcast', trophyId: 'community-shield', officialBallId: 'nile-pro', ceremonyTier: 'league', crowdMultiplier: 1.06, mediaMultiplier: 0.92, securityMultiplier: 1.02, musicStyle: 'Tense low-brass and percussion package', entranceStyle: 'minimal high-tension walkout', broadcastStyle: 'Survival Series', tiebreakers: ['goal-difference', 'away-goals', 'fair-play', 'lots'], extraTime: true, penalties: true, substitutions: 5, visualIdentity: 'Dark, tense presentation emphasizing stakes, aggregate score and survival.' },
]

export const VENUES: VenueProfile[] = [
  { id: 'addis-national', name: 'Addis National Arena', city: 'Addis Ababa', region: 'Addis Ababa', country: 'Ethiopia', archetype: 'national-bowl', capacity: 62000, altitudeM: 2400, roof: 'partial', tiers: 2, pitchDistanceM: 11, surfaceId: 'elite-hybrid', architecture: 'Monumental oval concrete bowl with renewed roof ring and national ceremonial axis.', surrounding: 'Dense urban avenues, light rail access, fan zones and highland skyline.', localLanguages: ['Amharic', 'English'], homeSupportShare: 0.76, awayAllocation: 0.08, vipShare: 0.05, familyShare: 0.12, roofCoverage: 0.38, crowdProximity: 0.6, openness: 0.72, reverbSeconds: 2.6, paEcho: 0.38, floodlightQuality: 0.92, drainage: 0.9, maintenanceBudget: 0.9, securityCapacity: 1, mediaCapacity: 1, accessibility: 0.82, hasTrack: true, hasRetractableRoof: false, benchStyle: 'integrated', screenCount: 2, exteriorDensity: 1, culturalDetails: ['Amharic wayfinding', 'Ethiopian flags', 'highland light', 'local food fan zone', 'national football history wall'] },
  { id: 'bahir-dar-lake', name: 'Bahir Dar Lake Arena', city: 'Bahir Dar', region: 'Amhara', country: 'Ethiopia', archetype: 'modern-arena', capacity: 45000, altitudeM: 1800, roof: 'partial', tiers: 2, pitchDistanceM: 7, surfaceId: 'highland-natural', architecture: 'Open-corner modern bowl with blue roof fins and strong lake-facing concourses.', surrounding: 'Palm-lined roads, lakeside atmosphere and regional vendor plazas.', localLanguages: ['Amharic'], homeSupportShare: 0.8, awayAllocation: 0.07, vipShare: 0.04, familyShare: 0.15, roofCoverage: 0.32, crowdProximity: 0.75, openness: 0.64, reverbSeconds: 2.3, paEcho: 0.32, floodlightQuality: 0.86, drainage: 0.84, maintenanceBudget: 0.78, securityCapacity: 0.86, mediaCapacity: 0.78, accessibility: 0.7, hasTrack: true, hasRetractableRoof: false, benchStyle: 'dugout', screenCount: 2, exteriorDensity: 0.72, culturalDetails: ['Lake-region color accents', 'Amharic signage', 'regional woven patterns', 'local coffee and food stalls'] },
  { id: 'hawassa-rift', name: 'Hawassa Rift Stadium', city: 'Hawassa', region: 'Sidama', country: 'Ethiopia', archetype: 'athletics-stadium', capacity: 36000, altitudeM: 1700, roof: 'partial', tiers: 1, pitchDistanceM: 13, surfaceId: 'highland-natural', architecture: 'Broad athletics bowl with light roof canopies and open landscaped ends.', surrounding: 'Rift Valley vegetation, lakeside roads and regional gathering spaces.', localLanguages: ['Sidama', 'Amharic'], homeSupportShare: 0.79, awayAllocation: 0.07, vipShare: 0.035, familyShare: 0.17, roofCoverage: 0.22, crowdProximity: 0.52, openness: 0.82, reverbSeconds: 1.8, paEcho: 0.26, floodlightQuality: 0.78, drainage: 0.8, maintenanceBudget: 0.7, securityCapacity: 0.78, mediaCapacity: 0.62, accessibility: 0.62, hasTrack: true, hasRetractableRoof: false, benchStyle: 'dugout', screenCount: 1, exteriorDensity: 0.54, culturalDetails: ['Sidama and Amharic signs', 'Rift Valley landscaping', 'regional patterns', 'family supporter zone'] },
  { id: 'adama-express', name: 'Adama Express Arena', city: 'Adama', region: 'Oromia', country: 'Ethiopia', archetype: 'compact-urban', capacity: 24000, altitudeM: 1700, roof: 'continuous', tiers: 1, pitchDistanceM: 5, surfaceId: 'elite-hybrid', architecture: 'Compact rectangular football-first ground with continuous shade canopy.', surrounding: 'Busy city roads, bus access, market streets and Oromo regional branding.', localLanguages: ['Afaan Oromo', 'Amharic'], homeSupportShare: 0.82, awayAllocation: 0.08, vipShare: 0.045, familyShare: 0.13, roofCoverage: 0.68, crowdProximity: 0.92, openness: 0.4, reverbSeconds: 2.8, paEcho: 0.4, floodlightQuality: 0.82, drainage: 0.88, maintenanceBudget: 0.74, securityCapacity: 0.8, mediaCapacity: 0.66, accessibility: 0.68, hasTrack: false, hasRetractableRoof: false, benchStyle: 'integrated', screenCount: 2, exteriorDensity: 0.82, culturalDetails: ['Afaan Oromo primary signage', 'Oromia color accents', 'urban supporter murals', 'local transit plaza'] },
  { id: 'dire-dawa-desert', name: 'Dire Dawa Railway Ground', city: 'Dire Dawa', region: 'Dire Dawa', country: 'Ethiopia', archetype: 'historic-ground', capacity: 19000, altitudeM: 1276, roof: 'partial', tiers: 1, pitchDistanceM: 6, surfaceId: 'regional-grass', architecture: 'Historic low concrete terraces with railway-era brick structures and new shaded stand.', surrounding: 'Dry urban streets, railway identity, warm evening light and mixed-language signage.', localLanguages: ['Somali', 'Amharic', 'Afaan Oromo'], homeSupportShare: 0.81, awayAllocation: 0.07, vipShare: 0.03, familyShare: 0.14, roofCoverage: 0.24, crowdProximity: 0.82, openness: 0.76, reverbSeconds: 1.55, paEcho: 0.2, floodlightQuality: 0.68, drainage: 0.64, maintenanceBudget: 0.56, securityCapacity: 0.7, mediaCapacity: 0.46, accessibility: 0.48, hasTrack: false, hasRetractableRoof: false, benchStyle: 'simple', screenCount: 1, exteriorDensity: 0.62, culturalDetails: ['Somali, Amharic and Oromo signage', 'railway heritage wall', 'shade canopies', 'local spice and tea vendors'] },
  { id: 'mekelle-highland', name: 'Mekelle Highland Stadium', city: 'Mekelle', region: 'Tigray', country: 'Ethiopia', archetype: 'athletics-stadium', capacity: 31000, altitudeM: 2084, roof: 'partial', tiers: 1, pitchDistanceM: 12, surfaceId: 'highland-natural', architecture: 'Highland oval with heavy masonry, covered central stand and wind-exposed ends.', surrounding: 'Rocky highland horizon, broad approach roads and regional gathering areas.', localLanguages: ['Tigrinya', 'Amharic'], homeSupportShare: 0.83, awayAllocation: 0.06, vipShare: 0.035, familyShare: 0.13, roofCoverage: 0.2, crowdProximity: 0.54, openness: 0.86, reverbSeconds: 1.65, paEcho: 0.24, floodlightQuality: 0.72, drainage: 0.7, maintenanceBudget: 0.62, securityCapacity: 0.78, mediaCapacity: 0.54, accessibility: 0.52, hasTrack: true, hasRetractableRoof: false, benchStyle: 'dugout', screenCount: 1, exteriorDensity: 0.46, culturalDetails: ['Tigrinya signage', 'highland stone textures', 'regional flags', 'wind-aware banners'] },
  { id: 'jimma-forest', name: 'Jimma Forest Ground', city: 'Jimma', region: 'Oromia', country: 'Ethiopia', archetype: 'historic-ground', capacity: 17000, altitudeM: 1780, roof: 'partial', tiers: 1, pitchDistanceM: 7, surfaceId: 'regional-grass', architecture: 'Traditional concrete stand with green roof, close terraces and tree-lined corners.', surrounding: 'Lush highland vegetation, coffee-region vendors and compact urban roads.', localLanguages: ['Afaan Oromo', 'Amharic'], homeSupportShare: 0.84, awayAllocation: 0.06, vipShare: 0.025, familyShare: 0.15, roofCoverage: 0.26, crowdProximity: 0.86, openness: 0.7, reverbSeconds: 1.9, paEcho: 0.27, floodlightQuality: 0.62, drainage: 0.58, maintenanceBudget: 0.48, securityCapacity: 0.66, mediaCapacity: 0.4, accessibility: 0.42, hasTrack: false, hasRetractableRoof: false, benchStyle: 'simple', screenCount: 1, exteriorDensity: 0.5, culturalDetails: ['Afaan Oromo signage', 'coffee-region identity', 'tree-lined supporter routes', 'local woven banners'] },
  { id: 'gondar-castle', name: 'Gondar Heritage Stadium', city: 'Gondar', region: 'Amhara', country: 'Ethiopia', archetype: 'historic-ground', capacity: 22000, altitudeM: 2133, roof: 'partial', tiers: 1, pitchDistanceM: 8, surfaceId: 'highland-natural', architecture: 'Stone-accented concrete bowl with historic-inspired portals and steep central stand.', surrounding: 'Highland city streets, heritage motifs and distant mountain silhouette.', localLanguages: ['Amharic'], homeSupportShare: 0.82, awayAllocation: 0.07, vipShare: 0.035, familyShare: 0.14, roofCoverage: 0.28, crowdProximity: 0.72, openness: 0.7, reverbSeconds: 2.05, paEcho: 0.3, floodlightQuality: 0.7, drainage: 0.72, maintenanceBudget: 0.58, securityCapacity: 0.72, mediaCapacity: 0.48, accessibility: 0.48, hasTrack: true, hasRetractableRoof: false, benchStyle: 'dugout', screenCount: 1, exteriorDensity: 0.5, culturalDetails: ['Amharic signage', 'heritage stone portals', 'historic football mural', 'highland sunset lighting'] },
  { id: 'bishoftu-academy', name: 'Bishoftu Football Centre', city: 'Bishoftu', region: 'Oromia', country: 'Ethiopia', archetype: 'training-centre', capacity: 4500, altitudeM: 1920, roof: 'open', tiers: 1, pitchDistanceM: 3, surfaceId: 'academy-artificial', architecture: 'Low academy stand, training buildings and multiple adjacent pitches.', surrounding: 'Lakeside training campus, trees, parking and team facilities.', localLanguages: ['Afaan Oromo', 'Amharic'], homeSupportShare: 0.7, awayAllocation: 0.12, vipShare: 0.02, familyShare: 0.2, roofCoverage: 0.08, crowdProximity: 0.92, openness: 0.94, reverbSeconds: 0.65, paEcho: 0.08, floodlightQuality: 0.66, drainage: 0.94, maintenanceBudget: 0.7, securityCapacity: 0.48, mediaCapacity: 0.28, accessibility: 0.62, hasTrack: false, hasRetractableRoof: false, benchStyle: 'touchline', screenCount: 0, exteriorDensity: 0.22, culturalDetails: ['Afaan Oromo signage', 'academy development wall', 'training equipment zones', 'family viewing berm'] },
  { id: 'university-campus', name: 'National University Ground', city: 'Addis Ababa', region: 'Addis Ababa', country: 'Ethiopia', archetype: 'university-ground', capacity: 9000, altitudeM: 2360, roof: 'partial', tiers: 1, pitchDistanceM: 5, surfaceId: 'regional-grass', architecture: 'Campus grandstand with academic colors, athletics lanes and student terraces.', surrounding: 'University buildings, pedestrian paths, campus trees and student gathering spaces.', localLanguages: ['Amharic', 'English'], homeSupportShare: 0.68, awayAllocation: 0.12, vipShare: 0.02, familyShare: 0.18, roofCoverage: 0.18, crowdProximity: 0.74, openness: 0.86, reverbSeconds: 1.05, paEcho: 0.14, floodlightQuality: 0.56, drainage: 0.62, maintenanceBudget: 0.44, securityCapacity: 0.52, mediaCapacity: 0.32, accessibility: 0.54, hasTrack: true, hasRetractableRoof: false, benchStyle: 'simple', screenCount: 1, exteriorDensity: 0.34, culturalDetails: ['Campus banners', 'student drum group', 'Amharic and English signage', 'school history display'] },
  { id: 'rural-highland', name: 'Highland Community Field', city: 'Regional District', region: 'Highlands', country: 'Ethiopia', archetype: 'rural-field', capacity: 1200, altitudeM: 2600, roof: 'open', tiers: 0, pitchDistanceM: 1.5, surfaceId: 'dry-community', architecture: 'Open grass field with earth banks, simple posts and temporary community benches.', surrounding: 'Mountains, farmland, trees, local road and small vendor shelters.', localLanguages: ['Amharic', 'Afaan Oromo'], homeSupportShare: 0.74, awayAllocation: 0.15, vipShare: 0, familyShare: 0.28, roofCoverage: 0, crowdProximity: 1, openness: 1, reverbSeconds: 0.2, paEcho: 0, floodlightQuality: 0.18, drainage: 0.38, maintenanceBudget: 0.16, securityCapacity: 0.18, mediaCapacity: 0.08, accessibility: 0.18, hasTrack: false, hasRetractableRoof: false, benchStyle: 'touchline', screenCount: 0, exteriorDensity: 0.06, culturalDetails: ['Community banners', 'children watching', 'local food table', 'mountain horizon', 'simple respectful presentation'] },
  { id: 'urban-street', name: 'Addis Urban Street Court', city: 'Addis Ababa', region: 'Addis Ababa', country: 'Ethiopia', archetype: 'street-court', capacity: 450, altitudeM: 2380, roof: 'open', tiers: 0, pitchDistanceM: 0.5, surfaceId: 'community-dirt', architecture: 'Fenced hard-dirt court between urban buildings with murals and simple lights.', surrounding: 'Neighbourhood streets, shops, minibuses, apartment blocks and local spectators.', localLanguages: ['Amharic'], homeSupportShare: 0.62, awayAllocation: 0.18, vipShare: 0, familyShare: 0.3, roofCoverage: 0, crowdProximity: 1, openness: 0.88, reverbSeconds: 0.45, paEcho: 0.05, floodlightQuality: 0.28, drainage: 0.24, maintenanceBudget: 0.08, securityCapacity: 0.12, mediaCapacity: 0.03, accessibility: 0.22, hasTrack: false, hasRetractableRoof: false, benchStyle: 'touchline', screenCount: 0, exteriorDensity: 0.94, culturalDetails: ['Amharic murals', 'local shops', 'children at fence', 'community referee table', 'urban traffic ambience'] },
  { id: 'indoor-futsal', name: 'Addis Indoor Futsal Hall', city: 'Addis Ababa', region: 'Addis Ababa', country: 'Ethiopia', archetype: 'futsal-arena', capacity: 6500, altitudeM: 2400, roof: 'indoor', tiers: 1, pitchDistanceM: 2, surfaceId: 'futsal-court', architecture: 'Compact enclosed hall with steep seating, roof trusses and full LED lighting.', surrounding: 'Urban sports complex, parking, food court and transit access.', localLanguages: ['Amharic', 'English'], homeSupportShare: 0.72, awayAllocation: 0.12, vipShare: 0.035, familyShare: 0.18, roofCoverage: 1, crowdProximity: 0.98, openness: 0.05, reverbSeconds: 3.1, paEcho: 0.52, floodlightQuality: 0.98, drainage: 1, maintenanceBudget: 0.78, securityCapacity: 0.64, mediaCapacity: 0.62, accessibility: 0.82, hasTrack: false, hasRetractableRoof: false, benchStyle: 'integrated', screenCount: 2, exteriorDensity: 0.75, culturalDetails: ['Amharic and English LED signage', 'indoor supporter drums', 'urban sports complex branding', 'family concourse'] },
]

export const DEFAULT_WORLD_SELECTION: WorldSelection = {
  competitionId: 'ethiopian-premier',
  venueId: 'addis-national',
  ballId: 'nile-pro',
  importance: 'regular',
  attendanceOverride: null,
  surfaceWear: 0.14,
  maintenanceQuality: 0.86,
  ceremonyEnabled: true,
  crowdChoreography: true,
  exteriorSequence: true,
  simplifiedPresentation: false,
  reducedPyro: false,
  highContrastBall: false,
}

export function getCompetition(id: string) { return COMPETITIONS.find((item) => item.id === id) ?? COMPETITIONS[0] }
export function getVenue(id: string) { return VENUES.find((item) => item.id === id) ?? VENUES[0] }
export function getSurface(id: string) { return SURFACES.find((item) => item.id === id) ?? SURFACES[0] }
export function getBall(id: string) { return BALLS.find((item) => item.id === id) ?? BALLS[0] }
export function getTrophy(id: string) { return TROPHIES.find((item) => item.id === id) ?? TROPHIES[0] }
